import React from 'react';
import { faUserNinja } from '@fortawesome/pro-light-svg-icons';

import Header from '../../components/Header';
import '../styles.scss';

/* eslint-disable max-len */
const PrivacyPolicy = () => (
  <React.Fragment>
    <Header title='Privacy Policy' icon={faUserNinja} />

    <div className='Page'>
      <p>No personal data is collected in the use of this site, except for low level data outlined below. This data is used to ensure performance and functionality of the services provided here.</p>

      <h2>Log Data</h2>
      <p>Log Data may include information such as your IP address, browser version, pages of the site that you visit, the time and date of your visit, the time spent on those pages, and other basic statistics.</p>

      <h2>Cookies / Local Storage</h2>
      <p>Cookies and Local Storage files are used to store data that is commonly used to maintain data across browser sessions. These files are generated by the site and are then provided to your browser to store. The site can then access these files to reload the state with your preferences and saved information.</p>

      <p>Cookies and Local Storage can be blocked within most major browsers either globally for all sites or on a site by site basis. If you decide to block access to these systems for this site, you may be unable to use some portions of the site.</p>
    </div>
  </React.Fragment>
);

export default PrivacyPolicy;
